#!/command/with-contenv bash
TOKEN_FILE = "${BASE_PATH}/adminui/token"
if [ -s "$TOKEN_FILE" ]; then
 BEARER_TOKEN=$(${BASE_PATH}/headscale/headscale apikey create)
 echo $BEARER_TOKEN > $TOKEN_FILE
fi
APP_PY_PATH="/app/config.py"
TOKEN_VALUE=$(cat "$TOKEN_FILE")
sed -i '/^BEARER_TOKEN/d' "$APP_PY_PATH"
echo "BEARER_TOKEN='$TOKEN_VALUE'" >> "$APP_PY_PATH"
python3 /app/app.py