services:  
  hs-admin:
    image: runyf/hs-admin:v2.8
    # image: hs-admin
    container_name: hs-admin  
    network_mode: host
    restart: unless-stopped  
    volumes:  
      - ~/hs-admin/app:/app
      - ~/hs-admin/config:/etc/headscale
      - ~/hs-admin/data:/var/lib/headscale
    environment:
      - TZ=Asia/Shanghai
